[package]
name = "nf"
edition = "2024"
version = "1.6.1"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.40", features = ["derive"] }
clap_complete = "4.5.54"
dirs = "6.0.0"
include_dir = "0.7.4"
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.8.23"
